# 端口
server:
  port: 8889

spring:
  profiles:
    active: weiran
  application:
    name: cloud-manage
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址 ,暂且只配置服务发现管理，配置管理暂且没有弄

logging:
  config: classpath:logback.xml