version: "3.9"

services:
  mission:
    build:
      context: ./cloud-mission
      dockerfile: Dockerfile-mission
    image: cloud-mission:1.0.0
    ports:
      - "8888:8888"
    environment:
      DOCKER_HOST: database
    links:
      - "mysql:database"
    depends_on:
      - mysql
    restart: always
    entrypoint: java -jar /app/cloud-mission.jar

  manage:
    build:
      context: ./cloud-manage
      dockerfile: Dockerfile-manage
    image: cloud-manage:1.0.0
    ports:
      - "8070:8070"
    environment:
      DOCKER_HOST: database
    links:
      - "mysql:database"
    depends_on:
      - mysql
    restart: always
    entrypoint: java -jar /app/cloud-manage.jar

  uaa:
    build:
      context: ./cloud-uaa
      dockerfile: Dockerfile-uaa
    image: cloud-uaa:1.0.0
    ports:
      - "8088:8088"
    environment:
      DOCKER_HOST: database
    links:
      - "mysql:database"
    depends_on:
      - mysql
    restart: always
    entrypoint: java -jar /app/cloud-uaa.jar

  gateway:
    build:
      context: ./cloud-gateway
      dockerfile: Dockerfile-gateway
    image: cloud-gateway:1.0.0
    ports:
      - "8205:8205"
    environment:
      DOCKER_HOST: database
    links:
      - "mysql:database"
    depends_on:
      - mysql
    restart: always
    entrypoint: java -jar /app/cloud-gateway.jar

  monitor:
    build:
      context: ./cloud-monitor
      dockerfile: Dockerfile-monitor
    image: cloud-monitor:1.0.0
    ports:
      - "8890:8890"
    environment:
      DOCKER_HOST: database
    links:
      - "mysql:database"
    depends_on:
      - mysql
    restart: always
    entrypoint: java -jar /app/cloud-monitor.jar

  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      # TODO 初始化多个sql脚本
      MYSQL_DATABASE: cloud-uaa
      TZ: Asia/Shanghai
    restart: always

  redis:
    image: redis:7.0
    volumes:
      - redis-data:/var/lib/redis
    ports:
      - "6379:6379"
    restart: always

  nacos:
    image: zhusaidong/nacos-server-m1:2.0.3
    ports:
      - "8848:8848"
    restart: always
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=
      - MYSQL_SERVICE_HOST=127.0.0.1
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
      - MYSQL_SERVICE_DB_PARAM=allowPublicKeyRetrieval=true

  namesrv:
    image: apacherocketmq/rocketmq:4.6.0
    container_name: rmqnamesrv
    restart: on-failure
    volumes:
      - mq-data:/var/lib/rocketmq
    ports:
      - 9876:9876
    environment:
      JAVA_OPT: -server -Xms256m -Xmx256m
    command: sh mqnamesrv

  broker:
    image: apacherocketmq/rocketmq:4.6.0
    container_name: rmqbroker
    restart: on-failure
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
    # 本地目录broker.conf 文件映射: 容器目录文件broker.conf
      - ./broker.conf:/home/rocketmq/conf/broker.conf
    command: sh mqbroker -n namesrv:9876 -c /home/rocketmq/conf/broker.conf
    depends_on:
      - namesrv

  rocketmq-console:
    image: candice0630/rocketmq-console-ng:2.0
    container_name: rmqconsole
    volumes:
      - mq-data:/var/lib/rocketmq
    restart: on-failure
    ports:
      - 19876:8080
    environment:
      JAVA_OPTS: -Drocketmq.config.namesrvAddr=namesrv:9876 -Drocketmq.config.isVIPChannel=false
    depends_on:
      - namesrv

volumes:
  mysql-data:
  redis-data:
  mq-data:
